version: 2
updates:
  - package-ecosystem: uv
    directory: /
    schedule:
      interval: weekly
    groups:
      python-runtime:
        applies-to: version-updates
        dependency-type: production
      python-dev:
        applies-to: version-updates
        dependency-type: development
      python-security:
        applies-to: security-updates
        patterns:
          - "*"
    labels:
      - dependencies
    open-pull-requests-limit: 10

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions:
        applies-to: version-updates
        patterns:
          - "*"
      github-actions-security:
        applies-to: security-updates
        patterns:
          - "*"
    labels:
      - dependencies
